name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

categories:
  - title: 'Feature'
    label: 'feature'
  - title: 'Enhancement'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
      - 'dependabot'
  - title: 'Pipeline'
    label: 'pipeline'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'dependabot'
      - 'enhancement'
  default: patch
