# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: OnPremQe

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadSecureFile@1
  displayName: 'Download RunSettings File'
  inputs:
    secureFile: 'Parallel.RunSettings'
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  inputs:
    versionSpec: '5.4.0'
- task: UseDotNet@2
  displayName: 'Download .Net Core v$(NetCoreVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(NetCoreVersion)'
    includePreviewVersions: true
    performMultiLevelLookup: true
- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    restoreSolution: 'Framework/Base.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  displayName: 'VS Build'
  inputs:
    solution: 'Framework/Base.sln'
    msbuildArgs: '/p:RunStyleCheck=1'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

