version: '2'

services:
  mongo:
    image: mongo
    restart: always    
    ports:
    - "27017:27017"
    volumes:
    - ./seed/seed.js:/docker-entrypoint-initdb.d/seed.js
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 